In [1]:
import pandas as pd
import json

# Analisis Argentina vs Colombia

En este notebook vamos a explorar datos basicos del partido y calcular algunas metricas iniciales.

In [23]:
df_partidos = pd.read_json(
    "../data/statsbomb/matches_223_282.json"
)

In [24]:
def obtener_nombre_local(equipo):
    return equipo["home_team_name"]

In [25]:
def obtener_nombre_visitante(equipo):
    return equipo["away_team_name"]

In [26]:
df_partidos["home_team_name"] = df_partidos["home_team"].apply(
    obtener_nombre_local
)

In [27]:
df_partidos["away_team_name"] = df_partidos["away_team"].apply(
    obtener_nombre_visitante
)

In [28]:
df_final = df_partidos[((df_partidos["home_team_name"] == "Argentina") & (df_partidos["away_team_name"] == "Colombia" )) | ((df_partidos["home_team_name"] == "Colombia") & (df_partidos["away_team_name"] == "Argentina"))]

df_final[
    [
        "match_id",
        "match_date",
        "home_team_name",
        "away_team_name",
        "home_score",
        "away_score"
    ]
]

    match_id  match_date home_team_name away_team_name  home_score  away_score
19   3943077  2024-07-15      Argentina       Colombia           1           0

In [29]:
match_id = df_final["match_id"].iloc[0]

match_id

np.int64(3943077)

## Eventos del partido

In [30]:
df_eventos = pd.read_json(
    "../data/statsbomb/events_3943077.json"
)

In [31]:
df_eventos.shape

(4146, 38)

In [32]:
df_eventos.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'player', 'position', 'location', 'pass',
       'carry', 'under_pressure', 'ball_receipt', 'shot', 'goalkeeper',
       'off_camera', 'out', 'clearance', 'dribble', 'duel', 'counterpress',
       'interception', 'foul_committed', 'foul_won', 'block', 'ball_recovery',
       '50_50', 'injury_stoppage', 'substitution', 'bad_behaviour'],
      dtype='str')

In [33]:
df_eventos.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,counterpress,interception,foul_committed,foul_won,block,ball_recovery,50_50,injury_stoppage,substitution,bad_behaviour
0,e1bf3ece-507f-4947-86bf-ec9c235b6d47,1,1,2026-08-19 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 779, 'name': 'Argentina'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,da60fb38-6413-4034-b79f-90c220f0d94c,2,1,2026-08-19 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 779, 'name': 'Argentina'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b8ea3c2c-6fb5-4f25-9fcb-9b112e9792f5,3,1,2026-08-19 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 779, 'name': 'Argentina'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,f2598369-c1e9-4d91-a03a-3deb8a0e74c7,4,1,2026-08-19 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 779, 'name': 'Argentina'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,e22de23d-c946-4123-a0f3-a9f8c749a35d,5,1,2026-08-19 00:00:00.525,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 779, 'name': 'Argentina'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_eventos[
    [
        "minute",
        "second",
        "type",
        "team",
        "player",
        "location"
    ]
].head(10)

,minute,second,type,team,player,location
0,0,0,"{'id': 35, 'name': 'Starting XI'}","{'id': 779, 'name': 'Argentina'}",NaN,NaN
1,0,0,"{'id': 35, 'name': 'Starting XI'}","{'id': 769, 'name': 'Colombia'}",NaN,NaN
2,0,0,"{'id': 18, 'name': 'Half Start'}","{'id': 779, 'name': 'Argentina'}",NaN,NaN
3,0,0,"{'id': 18, 'name': 'Half Start'}","{'id': 769, 'name': 'Colombia'}",NaN,NaN
4,0,0,"{'id': 30, 'name': 'Pass'}","{'id': 779, 'name': 'Argentina'}","{'id': 5503, 'name': 'Lionel Andrés Messi Cucc...","[61.0, 40.1]"
5,0,1,"{'id': 42, 'name': 'Ball Receipt*'}","{'id': 779, 'name': 'Argentina'}","{'id': 38718, 'name': 'Enzo Fernandez'}","[51.0, 40.0]"
6,0,1,"{'id': 43, 'name': 'Carry'}","{'id': 779, 'name': 'Argentina'}","{'id': 38718, 'name': 'Enzo Fernandez'}","[51.0, 40.0]"
7,0,2,"{'id': 30, 'name': 'Pass'}","{'id': 779, 'name': 'Argentina'}","{'id': 38718, 'name': 'Enzo Fernandez'}","[48.6, 41.0]"
8,0,2,"{'id': 42, 'name': 'Ball Receipt*'}","{'id': 779, 'name': 'Argentina'}","{'id': 7797, 'name': 'Rodrigo Javier De Paul'}","[45.6, 54.5]"
9,0,2,"{'id': 43, 'name': 'Carry'}","{'id': 779, 'name': 'Argentina'}","{'id': 7797, 'name': 'Rodrigo Javier De Paul'}","[45.6, 54.5]"

In [35]:
with open("../data/statsbomb/events_3943077.json", "r", encoding="utf-8") as archivo:
    datos_eventos = json.load(archivo)

In [36]:
df_eventos_normalizado = pd.json_normalize(datos_eventos)

In [37]:
df_eventos_normalizado[
    [
        "minute",
        "second",
        "type.name",
        "team.name",
        "player.name",
        "location"
    ]
].head(10)

,minute,second,type.name,team.name,player.name,location
0,0,0,Starting XI,Argentina,NaN,NaN
1,0,0,Starting XI,Colombia,NaN,NaN
2,0,0,Half Start,Argentina,NaN,NaN
3,0,0,Half Start,Colombia,NaN,NaN
4,0,0,Pass,Argentina,Lionel Andrés Messi Cuccittini,"[61.0, 40.1]"
5,0,1,Ball Receipt*,Argentina,Enzo Fernandez,"[51.0, 40.0]"
6,0,1,Carry,Argentina,Enzo Fernandez,"[51.0, 40.0]"
7,0,2,Pass,Argentina,Enzo Fernandez,"[48.6, 41.0]"
8,0,2,Ball Receipt*,Argentina,Rodrigo Javier De Paul,"[45.6, 54.5]"
9,0,2,Carry,Argentina,Rodrigo Javier De Paul,"[45.6, 54.5]"

In [38]:
df_eventos_normalizado["type.name"].unique()

<StringArray>
[      'Starting XI',        'Half Start',              'Pass',
     'Ball Receipt*',             'Carry',          'Pressure',
              'Shot',       'Goal Keeper',         'Clearance',
        'Miscontrol',             'Block',     'Dribbled Past',
           'Dribble',              'Duel',     'Ball Recovery',
      'Interception',    'Foul Committed',          'Foul Won',
      'Dispossessed',    'Tactical Shift',   'Injury Stoppage',
           'Offside',        'Player Off',         'Player On',
            'Shield',          'Half End',             '50/50',
 'Referee Ball-Drop',      'Substitution',     'Bad Behaviour']
Length: 30, dtype: str

In [39]:
df_eventos_normalizado["type.name"].value_counts()

type.name
Pass                 1197
Ball Receipt*        1114
Carry                 953
Pressure              313
Ball Recovery          93
Duel                   85
Block                  44
Goal Keeper            41
Dribble                39
Foul Committed         31
Shot                   30
Foul Won               30
Clearance              27
Dispossessed           25
Dribbled Past          23
Interception           21
Miscontrol             17
Substitution           12
Half Start              8
Half End                8
Referee Ball-Drop       8
Injury Stoppage         7
50/50                   6
Tactical Shift          4
Shield                  4
Starting XI             2
Offside                 1
Player Off              1
Player On               1
Bad Behaviour           1
Name: count, dtype: int64

In [40]:
df_tiros = df_eventos_normalizado[
    df_eventos_normalizado["type.name"] == "Shot"
]

df_tiros.shape

(30, 119)

In [41]:
[column for column in df_tiros.columns if column.startswith("shot.")]

['shot.statsbomb_xg',
 'shot.end_location',
 'shot.key_pass_id',
 'shot.body_part.id',
 'shot.body_part.name',
 'shot.type.id',
 'shot.type.name',
 'shot.outcome.id',
 'shot.outcome.name',
 'shot.first_time',
 'shot.technique.id',
 'shot.technique.name',
 'shot.freeze_frame',
 'shot.aerial_won',
 'shot.one_on_one']

In [42]:
df_tiros_limpio = df_tiros[
    [
        "minute",
        "second",
        "team.name",
        "player.name",
        "location",
        "shot.statsbomb_xg",
        "shot.outcome.name",
        "shot.body_part.name",
        "shot.type.name"
    ]
].copy()

df_tiros_limpio.head(10)

,minute,second,team.name,player.name,location,shot.statsbomb_xg,shot.outcome.name,shot.body_part.name,shot.type.name
36,0,36,Argentina,Julián Álvarez,"[105.6, 44.0]",0.072140,Off T,Right Foot,Open Play
184,4,56,Colombia,Luis Fernando Díaz Marulanda,"[98.6, 25.2]",0.029771,Saved,Right Foot,Open Play
243,6,12,Colombia,Jhon Andrés Córdoba Copete,"[105.5, 47.3]",0.075898,Post,Right Foot,Open Play
476,12,7,Colombia,Carlos Eccehomo Cuesta Figueroa,"[113.4, 38.7]",0.156862,Saved,Head,Open Play
834,19,43,Argentina,Lionel Andrés Messi Cuccittini,"[106.2, 36.8]",0.151331,Blocked,Left Foot,Open Play
1096,24,51,Colombia,Jhon Andrés Córdoba Copete,"[108.3, 39.0]",0.049562,Blocked,Head,Open Play
1334,32,19,Colombia,Jefferson Andrés Lerma Solís,"[85.6, 34.4]",0.015171,Saved,Right Foot,Open Play
1339,33,15,Colombia,Jhon Andrés Córdoba Copete,"[112.5, 42.5]",0.085104,Blocked,Head,Open Play
1517,39,22,Colombia,Jhon Adolfo Arias Andrade,"[106.1, 32.5]",0.025314,Wayward,Head,Open Play
1546,40,15,Colombia,Richard Rios Montoya,"[83.5, 48.0]",0.006474,Saved,Right Foot,Open Play

In [43]:
resumen_tiros = df_tiros_limpio.groupby("team.name").agg(
    tiros=("shot.statsbomb_xg", "count"),
    xg=("shot.statsbomb_xg", "sum")
)

resumen_tiros

           tiros        xg
team.name
Argentina     11  1.082702
Colombia      19  0.972254

In [44]:
resumen_tiros["xg_por_tiro"] = (
    resumen_tiros["xg"] / resumen_tiros["tiros"]
)

In [45]:
resumen_tiros = resumen_tiros.round(3)

resumen_tiros

           tiros     xg  xg_por_tiro
team.name
Argentina     11  1.083        0.098
Colombia      19  0.972        0.051