In [1]:
import pandas as pd
import json

# Analisis Argentina vs Colombia

En este notebook vamos a explorar datos basicos del partido y calcular algunas metricas iniciales.

In [2]:
df_partidos = pd.read_json(
    "../data/statsbomb/matches_223_282.json"
)

In [3]:
df_partidos.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee'],
      dtype='str')

In [4]:
df_partidos.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           32 non-null     int64
 1   match_date         32 non-null     str
 2   kick_off           32 non-null     str
 3   competition        32 non-null     object
 4   season             32 non-null     object
 5   home_team          32 non-null     object
 6   away_team          32 non-null     object
 7   home_score         32 non-null     int64
 8   away_score         32 non-null     int64
 9   match_status       32 non-null     str
 10  match_status_360   32 non-null     str
 11  last_updated       32 non-null     str
 12  last_updated_360   0 non-null      float64
 13  metadata           32 non-null     object
 14  match_week         32 non-null     int64
 15  competition_stage  32 non-null     object
 16  stadium            32 non-null     object
 17  referee            32 non-null     object
dtypes: float64(1), int64(4), object(8), str(5)
memory usage: 4.6+ KB

In [5]:
df_partidos["home_team"].iloc[0]

{'home_team_id': 781,
 'home_team_name': 'Brazil',
 'home_team_gender': 'male',
 'home_team_group': None,
 'country': {'id': 31, 'name': 'Brazil'},
 'managers': [{'id': 3239,
   'name': 'Dorival Silvestre Júnior',
   'nickname': 'Dorival Júnior',
   'dob': '1962-04-25',
   'country': {'id': 31, 'name': 'Brazil'}}]}

In [6]:
def obtener_nombre_local(equipo):
    return equipo["home_team_name"]

In [7]:
df_partidos["home_team_name"] = df_partidos["home_team"].apply(
    obtener_nombre_local
)

In [8]:
df_partidos[["home_team", "home_team_name"]].head()

                                           home_team home_team_name
0  {'home_team_id': 781, 'home_team_name': 'Brazi...         Brazil
1  {'home_team_id': 2305, 'home_team_name': 'Jama...        Jamaica
2  {'home_team_id': 783, 'home_team_name': 'Urugu...        Uruguay
3  {'home_team_id': 784, 'home_team_name': 'Peru'...           Peru
4  {'home_team_id': 3565, 'home_team_name': 'Ecua...        Ecuador

In [9]:
def obtener_nombre_visitante(equipo):
    return equipo["away_team_name"]

In [10]:
df_partidos["away_team_name"] = df_partidos["away_team"].apply(
    obtener_nombre_visitante
)

In [11]:
df_partidos[
    ["home_team_name", "away_team_name"]
].head()

  home_team_name away_team_name
0         Brazil       Colombia
1        Jamaica      Venezuela
2        Uruguay        Bolivia
3           Peru          Chile
4        Ecuador        Jamaica

In [ ]:
df_final = df_partidos[((df_partidos["home_team_name"] == "Argentina") & (df_partidos["away_team_name"] == "Colombia" )) | ((df_partidos["home_team_name"] == "Colombia") & (df_partidos["away_team_name"] == "Argentina"))]

df_final[
    [
        "match_id",
        "match_date",
        "home_team_name",
        "away_team_name",
        "home_score",
        "away_score"
    ]
]

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee,home_team_name,away_team_name
19,3943077,2024-07-15,01:15:00.000,"{'competition_id': 223, 'country_name': 'South...","{'season_id': 282, 'season_name': '2024'}","{'home_team_id': 779, 'home_team_name': 'Argen...","{'away_team_id': 769, 'away_team_name': 'Colom...",1,0,available,unscheduled,2026-04-28T19:57:53.484308,NaN,"{'data_version': '1.1.0', 'shot_fidelity_versi...",6,"{'id': 26, 'name': 'Final'}","{'id': 5337, 'name': 'Hard Rock Stadium', 'cou...","{'id': 2638, 'name': 'Raphael Claus', 'country...",Argentina,Colombia

In [16]:
match_id = df_final["match_id"].iloc[0]

match_id

np.int64(3943077)